/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bse_oop2_2025;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author jonah
 */
public class Add_vendor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Add_vendor.class.getName());

    /**
     * Creates new form Add_vendor
     */
    public Add_vendor() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Add Vendor");
        setupComboBox();
}

private void setupComboBox() {
    cmboxvendortype.removeAllItems(); 
    cmboxvendortype.addItem("Permanent");
    cmboxvendortype.addItem("Temporary");
    }
    
    public void saveVendor() {
    String firstName = txtfirstname.getText().trim(); 
    String lastName = txtlastname.getText().trim(); 
    String phone = txtphone.getText().trim(); 
    String vendorType = cmboxvendortype.getSelectedItem().toString(); 
    
    
    if (firstName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter first name!");
        txtfirstname.requestFocus();
        return;
    }
    
    if (lastName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter last name!");
        txtlastname.requestFocus();
        return;
    }
    
    if (phone.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter phone number!");
        txtphone.requestFocus();
        return;
    }
    
    
    if (!phone.matches("07[0-9]{8}")) {
        JOptionPane.showMessageDialog(this, "Please enter a valid phone number (07xxxxxxxx)!");
        txtphone.requestFocus();
        return;
    }
    
    try {
        Connection conn = DbConnection.getConnection();
        if (conn != null) {
            
            String checkSql = "SELECT * FROM vendors WHERE phone = ?";
            PreparedStatement checkPst = conn.prepareStatement(checkSql);
            checkPst.setString(1, phone);
            ResultSet rs = checkPst.executeQuery();
            
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Phone number already exists! Please use a different number.");
                txtphone.setText("");
                txtphone.requestFocus();
                return;
            }
            
            
            String sql = "INSERT INTO vendors (first_name, last_name, phone, vendor_type, status) VALUES (?, ?, ?, ?, 'Active')";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, firstName);
            pst.setString(2, lastName);
            pst.setString(3, phone);
            pst.setString(4, vendorType);
            
            int result = pst.executeUpdate();
            
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Vendor added successfully!");
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add vendor. Please try again.");
            }
            
            conn.close();
        } else {
            JOptionPane.showMessageDialog(this, "Database connection failed!");
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error saving vendor: " + ex.getMessage());
    }
}   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbfirstname = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        lblastname = new javax.swing.JLabel();
        txtlastname = new javax.swing.JTextField();
        lbphone = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        lbvendortype = new javax.swing.JLabel();
        cmboxvendortype = new javax.swing.JComboBox<>();
        btnsave = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbfirstname.setText("First Name");

        lblastname.setText("Last Name");

        lbphone.setText("Phone");

        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });

        lbvendortype.setText("Vendor Type");

        cmboxvendortype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmboxvendortype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboxvendortypeActionPerformed(evt);
            }
        });

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbvendortype)
                            .addComponent(lbphone)
                            .addComponent(lblastname)
                            .addComponent(lbfirstname))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtlastname, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                .addGap(8, 8, 8))
                            .addComponent(cmboxvendortype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfirstname)
                            .addComponent(txtphone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnsave))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btncancel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbfirstname)
                    .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblastname)
                    .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbphone)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbvendortype)
                    .addComponent(cmboxvendortype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnsave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncancel)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
       saveVendor();        // TODO add your handling code here:
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to go back? Any unsaved changes will be lost.", 
        "Confirm", 
        JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        this.setVisible(false);
        new MainDashBoard().setVisible(true);
    }

    }//GEN-LAST:event_btncancelActionPerformed

    private void cmboxvendortypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboxvendortypeActionPerformed
              // TODO add your handling code here:
    }//GEN-LAST:event_cmboxvendortypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Add_vendor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> cmboxvendortype;
    private javax.swing.JLabel lbfirstname;
    private javax.swing.JLabel lblastname;
    private javax.swing.JLabel lbphone;
    private javax.swing.JLabel lbvendortype;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
