/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bse_oop2_2025;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author jonah
 */
public class MainDashBoard extends javax.swing.JFrame {
    

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainDashBoard.class.getName());

    /**
     * Creates new form MainDashBoard
     */
    public MainDashBoard() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Main Dashboard");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnmanagevendors = new javax.swing.JButton();
        btnmanagestalls = new javax.swing.JButton();
        btncollectfees = new javax.swing.JButton();
        btnprocesspayments = new javax.swing.JButton();
        btnviewreports = new javax.swing.JButton();
        btnhandlecomplaints = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnmanagevendors.setText("Manage_vendors");
        btnmanagevendors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanagevendorsActionPerformed(evt);
            }
        });

        btnmanagestalls.setText("Manage_stalls");
        btnmanagestalls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanagestallsActionPerformed(evt);
            }
        });

        btncollectfees.setText("Collect_fees");
        btncollectfees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncollectfeesActionPerformed(evt);
            }
        });

        btnprocesspayments.setText("Process_payments");
        btnprocesspayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprocesspaymentsActionPerformed(evt);
            }
        });

        btnviewreports.setText("View_reports");
        btnviewreports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewreportsActionPerformed(evt);
            }
        });

        btnhandlecomplaints.setText("Handle_complaints");
        btnhandlecomplaints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhandlecomplaintsActionPerformed(evt);
            }
        });

        btnlogout.setText("Log_out");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnmanagevendors)
                    .addComponent(btnmanagestalls)
                    .addComponent(btncollectfees)
                    .addComponent(btnprocesspayments)
                    .addComponent(btnviewreports)
                    .addComponent(btnhandlecomplaints)
                    .addComponent(btnlogout))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnmanagevendors)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnmanagestalls)
                .addGap(18, 18, 18)
                .addComponent(btncollectfees)
                .addGap(18, 18, 18)
                .addComponent(btnprocesspayments)
                .addGap(18, 18, 18)
                .addComponent(btnviewreports)
                .addGap(18, 18, 18)
                .addComponent(btnhandlecomplaints)
                .addGap(18, 18, 18)
                .addComponent(btnlogout)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnviewreportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewreportsActionPerformed
        // TODO add your handling code here:
        try{
            new Reports().setVisible(true);
            this.setVisible(false);
        }catch(Exception e) {
            JOptionPane.showMessageDialog(this,"Error opening reports: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnviewreportsActionPerformed

    private void btnmanagevendorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanagevendorsActionPerformed
       
    
        // TODO add your handling code here:
        try {
            new Vendor_management().setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error opening vendor management: " + e.getMessage());
        }
    
    }//GEN-LAST:event_btnmanagevendorsActionPerformed

    private void btnmanagestallsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanagestallsActionPerformed
        // TODO add your handling code here:
        try {
            new StallManagement().setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error opening stall management: " + e.getMessage());
        }
    
    }//GEN-LAST:event_btnmanagestallsActionPerformed

    private void btncollectfeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncollectfeesActionPerformed
        try {
            new FeeCollection().setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error opening fee collection: " + e.getMessage());
        }
    }//GEN-LAST:event_btncollectfeesActionPerformed

    private void btnprocesspaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprocesspaymentsActionPerformed
        try {
            new Paymentform().setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error opening payment processing: " + e.getMessage());
        }
    }//GEN-LAST:event_btnprocesspaymentsActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to logout?", 
            "Confirm Logout", 
            JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            new User_login().setVisible(true);
        }
    
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnhandlecomplaintsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhandlecomplaintsActionPerformed
        // TODO add your handling code here:
        try{
            new ComplaintForm().setVisible(true);
            this.setVisible(false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error opening Complaints:" + e.getMessage());
        }
    }//GEN-LAST:event_btnhandlecomplaintsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainDashBoard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncollectfees;
    private javax.swing.JButton btnhandlecomplaints;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnmanagestalls;
    private javax.swing.JButton btnmanagevendors;
    private javax.swing.JButton btnprocesspayments;
    private javax.swing.JButton btnviewreports;
    // End of variables declaration//GEN-END:variables
}
