/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bse_oop2_2025;

/**
 *
 * @author jonah
 */
public class Vendor_management extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vendor_management.class.getName());

    /**
     * Creates new form Vendor_management
     */
    public Vendor_management() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnaddvendor = new javax.swing.JButton();
        btneditvendor = new javax.swing.JButton();
        btnviewdeatils = new javax.swing.JButton();
        btnassignproducts = new javax.swing.JButton();
        btnbacktodashboard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnaddvendor.setText("Add_new_vendor");
        btnaddvendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddvendorActionPerformed(evt);
            }
        });

        btneditvendor.setText("Edit_vendor");

        btnviewdeatils.setText("View_deatils");

        btnassignproducts.setText("Assign_products");

        btnbacktodashboard.setText("Back_to_dashboard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnviewdeatils)
                    .addComponent(btneditvendor)
                    .addComponent(btnaddvendor)
                    .addComponent(btnassignproducts)
                    .addComponent(btnbacktodashboard))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btnaddvendor)
                .addGap(18, 18, 18)
                .addComponent(btneditvendor)
                .addGap(18, 18, 18)
                .addComponent(btnviewdeatils)
                .addGap(18, 18, 18)
                .addComponent(btnassignproducts)
                .addGap(18, 18, 18)
                .addComponent(btnbacktodashboard)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddvendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddvendorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddvendorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Vendor_management().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddvendor;
    private javax.swing.JButton btnassignproducts;
    private javax.swing.JButton btnbacktodashboard;
    private javax.swing.JButton btneditvendor;
    private javax.swing.JButton btnviewdeatils;
    // End of variables declaration//GEN-END:variables
}
